# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NativeScript
email: eduardo.pisapia@synery-gb.com
description: > # this means to ignore newlines until "baseurl:"
  En la presente p치gina se busca introducir el Framework de desarrollo m칩vil NativeScript,
  ilustrando la elaboraci칩n de una aplicaci칩n para familiarizar a los desarrolladores
  con el framework.
baseurl: "/pas-restaurant-native-script" # the subpath of your site, e.g. /blog
url: "http://blog.synergy-gb.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  eppisapia

# Build settings
markdown: kramdown
